### ISSUE TITLE
Set diffrent name for rank not working

### ISSUE THREAD

**Issue by zadinvit** [plantagoIT/strapi-drag-drop-content-type-plugin#23]
Hi, 
we changed rank field name from rank to rankID, but button not showing on page. I found problems in functions in sort.js, because there was rank field hardcoded i changed index and update function to take rank field name from settings. 
But I still getting error from strapi database, there is not any function from your code in call stack.

Do you have any idea, where else i should change the rank? I search all usage rank in project and i can't find another usage which could cause the error.

My changes:

```async function index(contentType, start, limit, locale) {
  const settings = await getSettings();
  const sort = {};
  sort[settings.body.rank] = 'asc';
  return await strapi.entityService.findMany(contentType, {
    sort: sort,
    populate: '*',
    start: start,
    limit: limit,
    locale: locale,
  });
}

// Update rank of specified content type
async function update(id, contentType, rank) {
  const settings = await getSettings();
  const data = {};
  data[settings.body.rank] = rank;
  return await strapi.query(contentType).update({
    where: { id: id },
    data: data
  });
}```


error message:

 error: Attribute rank not found on model api::project.project
Error: Attribute rank not found on model api::project.project
    at /Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/query/helpers/order-by.js:36:15
    at Array.flatMap (<anonymous>)
    at processOrderBy (/Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/query/helpers/order-by.js:31:36)
    at /Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/query/helpers/order-by.js:27:39
    at Array.flatMap (<anonymous>)
    at Object.processOrderBy (/Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/query/helpers/order-by.js:27:20)
    at Object.processState (/Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/query/query-builder.js:301:31)
    at Object.getKnexQuery (/Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/query/query-builder.js:352:12)
    at Object.execute (/Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/query/query-builder.js:473:25)
    at Object.findMany (/Users/vit/Projects/Qubix_BE/node_modules/@strapi/database/lib/entity-manager/index.js:180:70)

**Comment by derschiw** [comment]
Oh gosh, this is in fact an issue. It's fixed in version 1.3.3 and released now.

**Comment by zadinvit** [comment]
@derschiw thanks for quick fix. I go test it.

**Comment by derschiw** [comment]
Thank you, I hope it works now!

**Comment by zadinvit** [comment]
Hi, button is now visible, but after click I see show more button and then titles blink and I getting this error again. So problem is still some where.

```
Attribute rank not found on model api::project.project
Error: Attribute rank not found on model api::project.project
```

**Comment by zadinvit** [comment]
@derschiw I using strapi version 4.5.2.
